// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


var canvas = (document.getElementById("canvas"));

var ctx = canvas.getContext("2d");

ctx.font = "16px IBM Plex Mono";

ctx.fillStyle = "white";

ctx.fillText("I like making software that users love.", 100, 100);

export {
  canvas ,
  ctx ,
  
}
/* canvas Not a pure module */
